---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: external-auth
  namespace: networking
spec:
  chain:
    middlewares:
      - name: auth-ak-outpost-traefik-default-xyz@kubernetescrd
      - name: chain-no-auth@kubernetescrd
