---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  KUBE_VIP_ADDR: "10.0.0.195"
  METALLB_LB_RANGE: "10.0.0.180-10.0.0.190"
  METALLB_K8S_GATEWAY_ADDR: "10.0.0.180"
  METALLB_INGRESS_ADDR: "10.0.0.181"
