apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-traefik
  namespace: flux-system
spec:
  path: ./cluster/apps/networking-system/traefik/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: networking-system-certificates
